name: Basic GitHub Actions
on:
  push:
    branch: main

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read & Output hello.txt
        run: |
          echo "hello.txt contains:"
          cat hello.txt
